# Generated by Django 2.0 on 2017-12-16 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageURL', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Meme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=300)),
                ('mainImage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mainImage', to='reviews.Image')),
                ('relatedImages', models.ManyToManyField(related_name='relatedImages', to='reviews.Image')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textReview', models.CharField(max_length=300)),
                ('titleReview', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='meme',
            name='reviews',
            field=models.ManyToManyField(to='reviews.Review'),
        ),
    ]
