# Generated by Django 2.0 on 2017-12-17 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_meme_datecreated'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='slug',
            field=models.SlugField(default='pepe', max_length=300),
            preserve_default=False,
        ),
    ]
